### ISSUE TITLE
Cocoapods can't be cached

### ISSUE THREAD

**Issue by ngAvaddon** [bitrise-steplib/steps-cache-push#23] opened 2019-03-21 17:43 UTC
iOS project set up in Bitrise. 

Updated from cache-push 2.0.5 -> 2.1.0. 
Failed on multiple different frameworks.

Rolling back to 2.0.5 fixed an issue.
Started to log errors: 

```
+------------------------------------------------------------------------------+
| (6) cache-push                                                               |
+------------------------------------------------------------------------------+
| id: cache-push                                                               |
| version: 2.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-03-20T23:27:28-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
bundle -> Gemfile.lock
Source/Pods -> Source/Podfile.lock
- IgnoredPaths: 
- CacheAPIURL: [REDACTED]
- FingerprintMethodID: file-content-hash
- CompressArchive: false
- DebugMode: true
Cleaning paths
Done in 393.565135ms
Checking previous cache status
Previous cache info found at: /tmp/cache-info.json
Done in 562.080833ms
Checking for file changes
Previous cache is invalid, new cache will be generated:
6 files needs to be removed
3812 files has changed
30 files added
File changes found in 4.971062ms
Generating cache archive
Failed to populate archive: read /Users/blabla/git/Source/Pods/RadarSDK/RadarSDK/RadarSDK.framework/Headers: is a directory
WARN[23:27:31] Step (cache-push) failed, but was marked as skippable 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ! | cache-push (exit code: 1)                                     | 4.54 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-cache-push/issues    |
| Source: https://github.com/bitrise-steplib/steps-cache-push.git              |
+---+---------------------------------------------------------------+----------+
```

**Comment by fehersanyi-bitrise** [comment] 2019-03-22 08:40
Hy there, the error says that the problem is that it is a directory, could you switch the compress archive on? so it zips the folder, maybe it can handle it that way? 🤔

**Comment by chbe89** [comment] 2019-03-22 13:16
I have a similar problem with a Carthage project. I tried to compress the archive. But without any result.

Then getting the error that the archive could not be written. `Failed to populate archive: archive/tar: write too long`

Downgrading from 2.1.0 to 2.0.5 fixed my problem.

```
+------------------------------------------------------------------------------+

| (7) cache-push                                                               |
+------------------------------------------------------------------------------+
| id: cache-push                                                               |
| version: 2.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-03-22T04:06:27-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- Paths: /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/cache278136532
./Carthage -> ./Carthage/Cachefile
.local/DerivedData
/Users/vagrant/git/Carthage -> /Users/vagrant/git/Carthage/Cachefile
- IgnoredPaths: 
- CacheAPIURL: [REDACTED]
- FingerprintMethodID: file-content-hash
- CompressArchive: true
- DebugMode: true
Cleaning paths
path does not exists at: /Users/vagrant/git/.local/DerivedData
Done in 537.27826ms
Checking previous cache status
No previous cache info found
Done in 452.671639ms
Generating cache archive
Failed to populate archive: archive/tar: write too long
WARN[04:06:32] Step (cache-push) failed, but was marked as skippable 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ! | cache-push (exit code: 1)                                     | 6.87 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-cache-push/issues    |
| Source: https://github.com/bitrise-steplib/steps-cache-push.git              |
+---+---------------------------------------------------------------+----------+
```

**Comment by ngAvaddon** [comment] 2019-03-22 16:36
I did try with both `Compress cache` **true** and **false**. Same results.

**Comment by fehersanyi-bitrise** [comment] 2019-03-25 09:07
Hy @ngAvaddon Could you please send me your latest build's url with this issue? so I can check the logs for some more detail?

**Comment by trapacska** [comment] 2019-03-25 15:53
@chbe89 could you please pass me the build url?

**Comment by chbe89** [comment] 2019-03-25 16:31
@fehersanyi-bitrise @trapacska https://app.bitrise.io/build/131b6ceb131dbeb3

**Comment by trapacska** [comment] 2019-03-26 09:16
@chbe89 @ngAvaddon thx for reporting. The issue is spotted and fixed in the new version of the step: https://github.com/bitrise-steplib/steps-cache-push/releases/tag/2.1.1 which going to be available within an hour.

Closing the issue but feel free to re-open if you still encounter any issues with it. 🚀

**Closed by trapacska** 2019-03-26 09:16 UTC
