### ISSUE TITLE
Error : No such file or directory

### ISSUE THREAD

**Issue by dag-io** [bitrise-steplib/steps-cache-push#2] opened 2016-04-27 20:49 UTC
### Context 

It's an Android project.
The build is available here : https://www.bitrise.io/build/e63b553468dc432c

### Config

```
    - cache-push@0.9.3:
        inputs:
        - cache_paths: "./.gradle"
        - fingerprint_method: file-mod-time
        - is_debug_mode: 'true'
```

### Error

```
rsync: change_dir "/root/.stepman/step_collections/1461397589/collection/steps/cache-push/0.9.3" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
FATA[20:21:03] [STEPMAN] - Failed to copy step.yml: exit status 23 
```

**Comment by viktorbenei** [comment] 2016-04-28 13:32
Thanks for reporting!

Can you please send us the full build log through the on-site chat (bottom right corner)?

**Comment by viktorbenei** [comment] 2016-04-28 14:07
Note: the issue is related to the StepLib URL - not the default was used, and in that StepLib (fork) the 0.9.3 version of the step was not available

Relevant log:

```
rsync: change_dir "/root/.stepman/step_collections/1461397589/collection/steps/cache-push/0.9.3" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
[31mFATA[0m[20:21:03] [STEPMAN] - Failed to copy step.yml: exit status 23 
+------------------------------------------------------------------------------+
| (6) cache-push@0.9.3                                                         |
+------------------------------------------------------------------------------+
| id: cache-push                                                               |
| version: 0.9.3                                                               |
| collection: https://github.com/dag-io/bitrise-steplib.git                    |
| time: 2016-04-27T20:21:03Z                                                   |
+------------------------------------------------------------------------------+
```

See the `collection` ;)

**Comment by viktorbenei** [comment] 2016-04-28 14:11
Closing this issue, as it's not related to this Step. Still investigating whether this might be caused by the CLI (version 1.3.2 of the Bitrise CLI was used)

**Closed by viktorbenei** 2016-04-28 14:11 UTC
